version: '3.8'

services:
  flask_app:
    container_name: flask_app
    image: abhaveabhilash/flask_app:latest
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - flask_db
    environment:
      - DATABASE_URL=postgresql://example_user:example_password@flask_db:5432/example_db

  flask_db:
    container_name: flask_db
    image: postgres:13
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  data: {}